FROM ros:noetic-ros-base-focal@sha256:72b8bc59035dc0a5b8e07aae28c16caa84192971d72d207c72ed734fb1d5e97d
RUN apt-get update && apt-get install -y --no-install-recommends git python3-pip python3-venv && rm -rf /var/lib/apt/lists/*
WORKDIR /workspaces/catkin_ws
CMD ["sleep", "infinity"]
